import { readdir, readFile, rm, mkdir } from 'node:fs/promises'
import { writeFileAtomic, WriteQueue } from './atomicWrite.js'
import { join } from 'node:path'
import { randomUUID } from 'node:crypto'
import { matchConversation } from '@shared/chatExport.js'
import { z } from 'zod'

/**
 * Conversation storage.
 *
 * One JSON file per conversation, behind this interface so the backing store can
 * become SQLite later without the UI noticing. Deliberately no native
 * dependency: `better-sqlite3` would force an electron-rebuild step into every
 * install for a feature that, at this scale, a directory of files handles fine.
 */

export const messageSchema = z.object({
  id: z.string(),
  role: z.enum(['system', 'user', 'assistant']),
  content: z.string(),
  createdAt: z.number(),
  /** Populated for assistant turns, so a conversation records how it was produced. */
  model: z.string().optional(),
  tokensPerSecond: z.number().optional(),
  /** Separate from content: reasoning models emit it, and it is collapsible in the UI. */
  reasoning: z.string().optional(),
  /**
   * Images attached to a user turn, as data URLs.
   *
   * Kept with the message rather than as separate files: a conversation stays a
   * single self-contained document, which is what makes the JSON store viable.
   * The trade-off is size, so the UI caps what it will attach.
   */
  images: z.array(z.string()).optional(),
  /**
   * Tools this turn called, with a one-line summary of each result. The full
   * result text is kept only for the most recent turn — older ones would be
   * re-sent on every message and fill the context with pages nobody reads.
   */
  toolCalls: z
    .array(
      z.object({
        id: z.string(),
        name: z.string(),
        argumentsJson: z.string(),
        summary: z.string().optional(),
        ok: z.boolean().optional(),
        sources: z.array(z.object({ title: z.string(), url: z.string() })).optional(),
        content: z.string().optional(),
        approxTokens: z.number().optional()
      })
    )
    .optional(),
  /** Set when generation was cut short, so a partial reply is not mistaken for a complete one. */
  stopped: z.boolean().optional(),
  /** The server's own token counts for the request that produced this turn. */
  usage: z
    .object({ promptTokens: z.number(), predictedTokens: z.number(), cacheTokens: z.number().optional() })
    .optional(),
  /** Generation ended because the context window filled, not because the model was done. */
  ranOutOfContext: z.boolean().optional(),
  error: z.string().optional()
})

/** Sampler settings travel with the conversation, so reopening one restores them. */
export const chatSettingsSchema = z.object({
  temperature: z.number().min(0).max(4).default(0.8),
  topP: z.number().min(0).max(1).default(0.95),
  topK: z.number().int().min(0).max(1000).default(40),
  minP: z.number().min(0).max(1).default(0.05),
  repeatPenalty: z.number().min(0).max(4).default(1.1),
  maxTokens: z.number().int().min(-1).max(1 << 20).default(-1)
})

export const DEFAULT_CHAT_SETTINGS = chatSettingsSchema.parse({})

export const conversationSchema = z.object({
  id: z.string(),
  title: z.string(),
  createdAt: z.number(),
  updatedAt: z.number(),
  systemPrompt: z.string().default(''),
  /** Tool names the model may call in this conversation. */
  tools: z.array(z.string().max(64)).max(64).default([]),
  messages: z.array(messageSchema).default([]),
  settings: chatSettingsSchema.default(DEFAULT_CHAT_SETTINGS),
  /**
   * A summary standing in for the oldest messages, once they no longer fit.
   * The messages themselves are kept — the transcript still shows everything —
   * but only the summary is sent to the model.
   */
  compaction: z
    .object({
      summary: z.string(),
      /** Everything up to and including this message is what the summary covers. */
      throughMessageId: z.string(),
      /** The user's own turns from that range, kept word for word. */
      userMessages: z.array(z.string()).default([]),
      messageCount: z.number(),
      at: z.number()
    })
    .nullable()
    .default(null),
  /** Whether to compact on its own when the window is nearly full. */
  autoCompact: z.boolean().default(true)
})

export type ChatSettings = z.infer<typeof chatSettingsSchema>
export type ChatMessage = z.infer<typeof messageSchema>
export type Conversation = z.infer<typeof conversationSchema>

/** Enough to render the sidebar without loading every message of every chat. */
export interface ConversationSummary {
  id: string
  title: string
  createdAt: number
  updatedAt: number
  messageCount: number
  preview: string
}

export class ConversationStore {
  /** One conversation can be saved from several places at once while streaming. */
  private readonly writes = new WriteQueue()

  constructor(private readonly dir: string) {}

  private file(id: string): string {
    // ids are generated by randomUUID, but this is a filesystem path built from
    // a value that crosses IPC, so it is constrained rather than trusted.
    if (!/^[a-f0-9-]{36}$/i.test(id)) throw new Error('invalid conversation id')
    return join(this.dir, `${id}.json`)
  }

  async init(): Promise<void> {
    await mkdir(this.dir, { recursive: true })
  }

  async list(): Promise<ConversationSummary[]> {
    let names: string[]
    try {
      names = await readdir(this.dir)
    } catch {
      return []
    }
    const out: ConversationSummary[] = []
    for (const name of names) {
      if (!name.endsWith('.json')) continue
      try {
        const c = conversationSchema.parse(JSON.parse(await readFile(join(this.dir, name), 'utf8')))
        const last = [...c.messages].reverse().find((m) => m.role !== 'system')
        out.push({
          id: c.id,
          title: c.title,
          createdAt: c.createdAt,
          updatedAt: c.updatedAt,
          messageCount: c.messages.length,
          preview: (last?.content ?? '').slice(0, 120).replace(/\s+/g, ' ').trim()
        })
      } catch {
        // A corrupt file should not take down the whole sidebar.
      }
    }
    return out.sort((a, b) => b.updatedAt - a.updatedAt)
  }

  /**
   * Conversations matching every word of `query`, in their titles or their
   * messages, newest first, each with the line where it matched. Reads every
   * file, which a few hundred chats make cheap; the sidebar asks once typing
   * pauses, not per key.
   */
  async search(query: string): Promise<Array<ConversationSummary & { where: 'title' | 'message'; snippet: string }>> {
    if (!query.trim()) return []
    let names: string[]
    try {
      names = await readdir(this.dir)
    } catch {
      return []
    }
    const hits: Array<ConversationSummary & { where: 'title' | 'message'; snippet: string }> = []
    for (const name of names) {
      if (!name.endsWith('.json')) continue
      try {
        const c = conversationSchema.parse(JSON.parse(await readFile(join(this.dir, name), 'utf8')))
        const match = matchConversation(c, query)
        if (!match) continue
        const last = [...c.messages].reverse().find((m) => m.role !== 'system')
        hits.push({
          id: c.id, title: c.title, createdAt: c.createdAt, updatedAt: c.updatedAt, messageCount: c.messages.length,
          preview: (last?.content ?? '').slice(0, 120).replace(/\s+/g, ' ').trim(),
          ...match
        })
      } catch {
        // As in list(): one bad file does not hide the rest.
      }
    }
    return hits.sort((a, b) => b.updatedAt - a.updatedAt)
  }

  async get(id: string): Promise<Conversation | null> {
    try {
      return conversationSchema.parse(JSON.parse(await readFile(this.file(id), 'utf8')))
    } catch {
      return null
    }
  }

  async save(conversation: Conversation): Promise<Conversation> {
    const parsed = conversationSchema.parse({ ...conversation, updatedAt: Date.now() })
    await this.writes.run(() =>
      writeFileAtomic(this.file(parsed.id), JSON.stringify(parsed, null, 2))
    )
    return parsed
  }

  /** `tools` is carried over from the chat you were in, so a new one is usable straight away. */
  async create(systemPrompt = '', tools: string[] = []): Promise<Conversation> {
    const now = Date.now()
    return this.save({
      id: randomUUID(),
      title: 'New chat',
      createdAt: now,
      updatedAt: now,
      systemPrompt,
      tools,
      messages: [],
      settings: DEFAULT_CHAT_SETTINGS,
      compaction: null,
      autoCompact: true
    })
  }

  async remove(id: string): Promise<void> {
    await rm(this.file(id), { force: true })
  }
}

/** First user message, trimmed to something that fits a sidebar row. */
export function deriveTitle(text: string): string {
  const clean = text.replace(/\s+/g, ' ').trim()
  if (!clean) return 'New chat'
  return clean.length > 48 ? `${clean.slice(0, 48)}…` : clean
}
